# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ruby_viaggiatreno_microservizio/viaggiatreno_service.proto for package 'Trenical.RubyViaggiatreno'

require 'grpc'
require 'ruby_viaggiatreno_microservizio/viaggiatreno_service_pb'

module Trenical
  module RubyViaggiatreno
    module ViaggiatrenoService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'proto.ruby_viaggiatreno_microservizio.ViaggiatrenoService'

        rpc :GetTrainRealtimeStatus, ::Trenical::RubyViaggiatreno::TrainStatusRequest, ::Trenical::RubyViaggiatreno::TrainStatusResponse
        rpc :SearchStations, ::Trenical::RubyViaggiatreno::SearchStationRequest, ::Trenical::RubyViaggiatreno::StationListResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
