# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: viaggiatreno_service.proto

require 'google/protobuf'


descriptor_data = "\n\x1aviaggiatreno_service.proto\x12%proto.ruby_viaggiatreno_microservizio\"*\n\x12TrainStatusRequest\x12\x14\n\x0ctrain_number\x18\x01 \x01(\t\"\x91\x03\n\x13TrainStatusResponse\x12\x14\n\x0ctrain_number\x18\x01 \x01(\t\x12\x16\n\x0etrain_category\x18\x02 \x01(\t\x12\x16\n\x0eorigin_station\x18\x03 \x01(\t\x12\x1b\n\x13\x64\x65stination_station\x18\x04 \x01(\t\x12 \n\x18scheduled_departure_time\x18\x05 \x01(\t\x12\x1e\n\x16scheduled_arrival_time\x18\x06 \x01(\t\x12\x1d\n\x15\x61\x63tual_departure_time\x18\x07 \x01(\t\x12\x1b\n\x13\x61\x63tual_arrival_time\x18\x08 \x01(\t\x12\x15\n\rdelay_minutes\x18\t \x01(\x05\x12\x1d\n\x15last_detected_station\x18\n \x01(\t\x12\x1b\n\x13last_detection_time\x18\x0b \x01(\t\x12 \n\x18train_status_description\x18\x0c \x01(\t\x12\r\n\x05\x66ound\x18\r \x01(\x08\x12\x15\n\rerror_message\x18\x0e \x01(\t2\xa7\x01\n\x13ViaggiatrenoService\x12\x8f\x01\n\x16GetTrainRealtimeStatus\x12\x39.proto.ruby_viaggiatreno_microservizio.TrainStatusRequest\x1a:.proto.ruby_viaggiatreno_microservizio.TrainStatusResponseB@\n\x1fruby_viaggiatreno_microservizioP\x01\xea\x02\x1aTrenical::RubyViaggiatrenob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Trenical
  module RubyViaggiatreno
    TrainStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ruby_viaggiatreno_microservizio.TrainStatusRequest").msgclass
    TrainStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ruby_viaggiatreno_microservizio.TrainStatusResponse").msgclass
  end
end
